// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: app_game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//给全服用户发送消息
type SendAllMsgToLocalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendAllMsgToLocalRequest) Reset() {
	*x = SendAllMsgToLocalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAllMsgToLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAllMsgToLocalRequest) ProtoMessage() {}

func (x *SendAllMsgToLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAllMsgToLocalRequest.ProtoReflect.Descriptor instead.
func (*SendAllMsgToLocalRequest) Descriptor() ([]byte, []int) {
	return file_app_game_proto_rawDescGZIP(), []int{0}
}

func (x *SendAllMsgToLocalRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendAllReply) Reset() {
	*x = SendAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAllReply) ProtoMessage() {}

func (x *SendAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAllReply.ProtoReflect.Descriptor instead.
func (*SendAllReply) Descriptor() ([]byte, []int) {
	return file_app_game_proto_rawDescGZIP(), []int{1}
}

// 给单个用户发送消息
type SendUserMsgToLocalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendUserMsgToLocalRequest) Reset() {
	*x = SendUserMsgToLocalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendUserMsgToLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMsgToLocalRequest) ProtoMessage() {}

func (x *SendUserMsgToLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserMsgToLocalRequest.ProtoReflect.Descriptor instead.
func (*SendUserMsgToLocalRequest) Descriptor() ([]byte, []int) {
	return file_app_game_proto_rawDescGZIP(), []int{2}
}

func (x *SendUserMsgToLocalRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendUserMsgToLocalRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendUserReply) Reset() {
	*x = SendUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserReply) ProtoMessage() {}

func (x *SendUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserReply.ProtoReflect.Descriptor instead.
func (*SendUserReply) Descriptor() ([]byte, []int) {
	return file_app_game_proto_rawDescGZIP(), []int{3}
}

// 给小组用户发送消息
type SendGroupMsgToLocalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendGroupMsgToLocalRequest) Reset() {
	*x = SendGroupMsgToLocalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMsgToLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMsgToLocalRequest) ProtoMessage() {}

func (x *SendGroupMsgToLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMsgToLocalRequest.ProtoReflect.Descriptor instead.
func (*SendGroupMsgToLocalRequest) Descriptor() ([]byte, []int) {
	return file_app_game_proto_rawDescGZIP(), []int{4}
}

func (x *SendGroupMsgToLocalRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendGroupMsgToLocalRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendGroupReply) Reset() {
	*x = SendGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupReply) ProtoMessage() {}

func (x *SendGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupReply.ProtoReflect.Descriptor instead.
func (*SendGroupReply) Descriptor() ([]byte, []int) {
	return file_app_game_proto_rawDescGZIP(), []int{5}
}

var File_app_game_proto protoreflect.FileDescriptor

var file_app_game_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x70, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x2e, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4d,
	0x73, 0x67, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x47, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4a,
	0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x54, 0x6f,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65,
	0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xe7, 0x01, 0x0a,
	0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x1d,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54,
	0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x73, 0x67, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_game_proto_rawDescOnce sync.Once
	file_app_game_proto_rawDescData = file_app_game_proto_rawDesc
)

func file_app_game_proto_rawDescGZIP() []byte {
	file_app_game_proto_rawDescOnce.Do(func() {
		file_app_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_game_proto_rawDescData)
	})
	return file_app_game_proto_rawDescData
}

var file_app_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_game_proto_goTypes = []interface{}{
	(*SendAllMsgToLocalRequest)(nil),   // 0: pb.SendAllMsgToLocalRequest
	(*SendAllReply)(nil),               // 1: pb.SendAllReply
	(*SendUserMsgToLocalRequest)(nil),  // 2: pb.SendUserMsgToLocalRequest
	(*SendUserReply)(nil),              // 3: pb.SendUserReply
	(*SendGroupMsgToLocalRequest)(nil), // 4: pb.SendGroupMsgToLocalRequest
	(*SendGroupReply)(nil),             // 5: pb.SendGroupReply
}
var file_app_game_proto_depIdxs = []int32{
	2, // 0: pb.Greeter.SendUserMsgToLocal:input_type -> pb.SendUserMsgToLocalRequest
	4, // 1: pb.Greeter.SendGroupMsgToLocal:input_type -> pb.SendGroupMsgToLocalRequest
	0, // 2: pb.Greeter.SendAllMsgToLocal:input_type -> pb.SendAllMsgToLocalRequest
	3, // 3: pb.Greeter.SendUserMsgToLocal:output_type -> pb.SendUserReply
	5, // 4: pb.Greeter.SendGroupMsgToLocal:output_type -> pb.SendGroupReply
	1, // 5: pb.Greeter.SendAllMsgToLocal:output_type -> pb.SendAllReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_game_proto_init() }
func file_app_game_proto_init() {
	if File_app_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAllMsgToLocalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendUserMsgToLocalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMsgToLocalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_game_proto_goTypes,
		DependencyIndexes: file_app_game_proto_depIdxs,
		MessageInfos:      file_app_game_proto_msgTypes,
	}.Build()
	File_app_game_proto = out.File
	file_app_game_proto_rawDesc = nil
	file_app_game_proto_goTypes = nil
	file_app_game_proto_depIdxs = nil
}
